# Generated by Django 5.0.6 on 2024-06-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.ImageField(upload_to='images_product', verbose_name='Фото'),
        ),
    ]
