# Generated by Django 5.0.6 on 2024-06-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_slug',
            new_name='product_image',
        ),
    ]
